# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake

# The command to remove a file.
RM = /nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /share/sources/Cubed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /share/sources/Cubed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /share/sources/Cubed/CMakeFiles /share/sources/Cubed//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /share/sources/Cubed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Walnut-Networking

# Build rule for target.
Walnut-Networking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Walnut-Networking
.PHONY : Walnut-Networking

# fast build rule for target.
Walnut-Networking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/build
.PHONY : Walnut-Networking/fast

#=============================================================================
# Target rules for targets named Cubed-Common-Headless

# Build rule for target.
Cubed-Common-Headless: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cubed-Common-Headless
.PHONY : Cubed-Common-Headless

# fast build rule for target.
Cubed-Common-Headless/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Common-Headless.dir/build.make CMakeFiles/Cubed-Common-Headless.dir/build
.PHONY : Cubed-Common-Headless/fast

#=============================================================================
# Target rules for targets named Cubed-Server

# Build rule for target.
Cubed-Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cubed-Server
.PHONY : Cubed-Server

# fast build rule for target.
Cubed-Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/build
.PHONY : Cubed-Server/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named Walnut-Headless

# Build rule for target.
Walnut-Headless: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Walnut-Headless
.PHONY : Walnut-Headless

# fast build rule for target.
Walnut-Headless/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/build
.PHONY : Walnut-Headless/fast

Cubed-Common/Source/ServerPacket.o: Cubed-Common/Source/ServerPacket.cpp.o
.PHONY : Cubed-Common/Source/ServerPacket.o

# target to build an object file
Cubed-Common/Source/ServerPacket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Common-Headless.dir/build.make CMakeFiles/Cubed-Common-Headless.dir/Cubed-Common/Source/ServerPacket.cpp.o
.PHONY : Cubed-Common/Source/ServerPacket.cpp.o

Cubed-Common/Source/ServerPacket.i: Cubed-Common/Source/ServerPacket.cpp.i
.PHONY : Cubed-Common/Source/ServerPacket.i

# target to preprocess a source file
Cubed-Common/Source/ServerPacket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Common-Headless.dir/build.make CMakeFiles/Cubed-Common-Headless.dir/Cubed-Common/Source/ServerPacket.cpp.i
.PHONY : Cubed-Common/Source/ServerPacket.cpp.i

Cubed-Common/Source/ServerPacket.s: Cubed-Common/Source/ServerPacket.cpp.s
.PHONY : Cubed-Common/Source/ServerPacket.s

# target to generate assembly for a file
Cubed-Common/Source/ServerPacket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Common-Headless.dir/build.make CMakeFiles/Cubed-Common-Headless.dir/Cubed-Common/Source/ServerPacket.cpp.s
.PHONY : Cubed-Common/Source/ServerPacket.cpp.s

Cubed-Server/Source/CubedApp.o: Cubed-Server/Source/CubedApp.cpp.o
.PHONY : Cubed-Server/Source/CubedApp.o

# target to build an object file
Cubed-Server/Source/CubedApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/CubedApp.cpp.o
.PHONY : Cubed-Server/Source/CubedApp.cpp.o

Cubed-Server/Source/CubedApp.i: Cubed-Server/Source/CubedApp.cpp.i
.PHONY : Cubed-Server/Source/CubedApp.i

# target to preprocess a source file
Cubed-Server/Source/CubedApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/CubedApp.cpp.i
.PHONY : Cubed-Server/Source/CubedApp.cpp.i

Cubed-Server/Source/CubedApp.s: Cubed-Server/Source/CubedApp.cpp.s
.PHONY : Cubed-Server/Source/CubedApp.s

# target to generate assembly for a file
Cubed-Server/Source/CubedApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/CubedApp.cpp.s
.PHONY : Cubed-Server/Source/CubedApp.cpp.s

Cubed-Server/Source/HeadlessConsole.o: Cubed-Server/Source/HeadlessConsole.cpp.o
.PHONY : Cubed-Server/Source/HeadlessConsole.o

# target to build an object file
Cubed-Server/Source/HeadlessConsole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/HeadlessConsole.cpp.o
.PHONY : Cubed-Server/Source/HeadlessConsole.cpp.o

Cubed-Server/Source/HeadlessConsole.i: Cubed-Server/Source/HeadlessConsole.cpp.i
.PHONY : Cubed-Server/Source/HeadlessConsole.i

# target to preprocess a source file
Cubed-Server/Source/HeadlessConsole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/HeadlessConsole.cpp.i
.PHONY : Cubed-Server/Source/HeadlessConsole.cpp.i

Cubed-Server/Source/HeadlessConsole.s: Cubed-Server/Source/HeadlessConsole.cpp.s
.PHONY : Cubed-Server/Source/HeadlessConsole.s

# target to generate assembly for a file
Cubed-Server/Source/HeadlessConsole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/HeadlessConsole.cpp.s
.PHONY : Cubed-Server/Source/HeadlessConsole.cpp.s

Cubed-Server/Source/ServerLayer.o: Cubed-Server/Source/ServerLayer.cpp.o
.PHONY : Cubed-Server/Source/ServerLayer.o

# target to build an object file
Cubed-Server/Source/ServerLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/ServerLayer.cpp.o
.PHONY : Cubed-Server/Source/ServerLayer.cpp.o

Cubed-Server/Source/ServerLayer.i: Cubed-Server/Source/ServerLayer.cpp.i
.PHONY : Cubed-Server/Source/ServerLayer.i

# target to preprocess a source file
Cubed-Server/Source/ServerLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/ServerLayer.cpp.i
.PHONY : Cubed-Server/Source/ServerLayer.cpp.i

Cubed-Server/Source/ServerLayer.s: Cubed-Server/Source/ServerLayer.cpp.s
.PHONY : Cubed-Server/Source/ServerLayer.s

# target to generate assembly for a file
Cubed-Server/Source/ServerLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cubed-Server.dir/build.make CMakeFiles/Cubed-Server.dir/Cubed-Server/Source/ServerLayer.cpp.s
.PHONY : Cubed-Server/Source/ServerLayer.cpp.s

Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.o: Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.o

# target to build an object file
Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.o

Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.i: Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.i

# target to preprocess a source file
Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.i

Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.s: Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.s

# target to generate assembly for a file
Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.cpp.s

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.o: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.o

# target to build an object file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.o

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.i: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.i

# target to preprocess a source file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.i

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.s: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.s

# target to generate assembly for a file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.cpp.s

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.o: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.o

# target to build an object file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.o

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.i: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.i

# target to preprocess a source file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.i

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.s: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.s

# target to generate assembly for a file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.cpp.s

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.o: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.o

# target to build an object file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.o
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.o

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.i: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.i

# target to preprocess a source file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.i
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.i

Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.s: Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.s

# target to generate assembly for a file
Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Networking.dir/build.make CMakeFiles/Walnut-Networking.dir/Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.s
.PHONY : Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.cpp.s

Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.o: Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.o
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.o

# target to build an object file
Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.o
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.o

Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.i: Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.i
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.i

# target to preprocess a source file
Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.i
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.i

Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.s: Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.s
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.s

# target to generate assembly for a file
Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.s
.PHONY : Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.cpp.s

Walnut/Walnut/Source/Walnut/Core/Log.o: Walnut/Walnut/Source/Walnut/Core/Log.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Core/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Core/Log.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.cpp.o

Walnut/Walnut/Source/Walnut/Core/Log.i: Walnut/Walnut/Source/Walnut/Core/Log.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Core/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Core/Log.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.cpp.i

Walnut/Walnut/Source/Walnut/Core/Log.s: Walnut/Walnut/Source/Walnut/Core/Log.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Core/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Core/Log.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Core/Log.cpp.s

Walnut/Walnut/Source/Walnut/Random.o: Walnut/Walnut/Source/Walnut/Random.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Random.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Random.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Random.cpp.o

Walnut/Walnut/Source/Walnut/Random.i: Walnut/Walnut/Source/Walnut/Random.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Random.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Random.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Random.cpp.i

Walnut/Walnut/Source/Walnut/Random.s: Walnut/Walnut/Source/Walnut/Random.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Random.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Random.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Random.cpp.s

Walnut/Walnut/Source/Walnut/Serialization/BufferStream.o: Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.o

Walnut/Walnut/Source/Walnut/Serialization/BufferStream.i: Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.i

Walnut/Walnut/Source/Walnut/Serialization/BufferStream.s: Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/BufferStream.cpp.s

Walnut/Walnut/Source/Walnut/Serialization/FileStream.o: Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.o

Walnut/Walnut/Source/Walnut/Serialization/FileStream.i: Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.i

Walnut/Walnut/Source/Walnut/Serialization/FileStream.s: Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/FileStream.cpp.s

Walnut/Walnut/Source/Walnut/Serialization/StreamReader.o: Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.o

Walnut/Walnut/Source/Walnut/Serialization/StreamReader.i: Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.i

Walnut/Walnut/Source/Walnut/Serialization/StreamReader.s: Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamReader.cpp.s

Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.o: Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.o

Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.i: Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.i

Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.s: Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.cpp.s

Walnut/Walnut/Source/Walnut/Utils/StringUtils.o: Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.o

# target to build an object file
Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.o
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.o

Walnut/Walnut/Source/Walnut/Utils/StringUtils.i: Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.i

# target to preprocess a source file
Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.i
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.i

Walnut/Walnut/Source/Walnut/Utils/StringUtils.s: Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.s

# target to generate assembly for a file
Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut-Headless.dir/build.make CMakeFiles/Walnut-Headless.dir/Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.s
.PHONY : Walnut/Walnut/Source/Walnut/Utils/StringUtils.cpp.s

Walnut/vendor/yaml-cpp/src/binary.o: Walnut/vendor/yaml-cpp/src/binary.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/binary.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/binary.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/binary.cpp.o

Walnut/vendor/yaml-cpp/src/binary.i: Walnut/vendor/yaml-cpp/src/binary.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/binary.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/binary.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/binary.cpp.i

Walnut/vendor/yaml-cpp/src/binary.s: Walnut/vendor/yaml-cpp/src/binary.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/binary.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/binary.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/binary.cpp.s

Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.o: Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.o

Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.i: Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.i

Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.s: Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.cpp.s

Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.o: Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.o

Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.i: Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.i

Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.s: Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.cpp.s

Walnut/vendor/yaml-cpp/src/convert.o: Walnut/vendor/yaml-cpp/src/convert.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/convert.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/convert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/convert.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/convert.cpp.o

Walnut/vendor/yaml-cpp/src/convert.i: Walnut/vendor/yaml-cpp/src/convert.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/convert.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/convert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/convert.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/convert.cpp.i

Walnut/vendor/yaml-cpp/src/convert.s: Walnut/vendor/yaml-cpp/src/convert.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/convert.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/convert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/convert.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/convert.cpp.s

Walnut/vendor/yaml-cpp/src/depthguard.o: Walnut/vendor/yaml-cpp/src/depthguard.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/depthguard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/depthguard.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.cpp.o

Walnut/vendor/yaml-cpp/src/depthguard.i: Walnut/vendor/yaml-cpp/src/depthguard.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/depthguard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/depthguard.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.cpp.i

Walnut/vendor/yaml-cpp/src/depthguard.s: Walnut/vendor/yaml-cpp/src/depthguard.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/depthguard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/depthguard.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/depthguard.cpp.s

Walnut/vendor/yaml-cpp/src/directives.o: Walnut/vendor/yaml-cpp/src/directives.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/directives.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/directives.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/directives.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/directives.cpp.o

Walnut/vendor/yaml-cpp/src/directives.i: Walnut/vendor/yaml-cpp/src/directives.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/directives.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/directives.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/directives.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/directives.cpp.i

Walnut/vendor/yaml-cpp/src/directives.s: Walnut/vendor/yaml-cpp/src/directives.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/directives.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/directives.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/directives.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/directives.cpp.s

Walnut/vendor/yaml-cpp/src/emit.o: Walnut/vendor/yaml-cpp/src/emit.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emit.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/emit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emit.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emit.cpp.o

Walnut/vendor/yaml-cpp/src/emit.i: Walnut/vendor/yaml-cpp/src/emit.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emit.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/emit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emit.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emit.cpp.i

Walnut/vendor/yaml-cpp/src/emit.s: Walnut/vendor/yaml-cpp/src/emit.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emit.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/emit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emit.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emit.cpp.s

Walnut/vendor/yaml-cpp/src/emitfromevents.o: Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.o

Walnut/vendor/yaml-cpp/src/emitfromevents.i: Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.i

Walnut/vendor/yaml-cpp/src/emitfromevents.s: Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitfromevents.cpp.s

Walnut/vendor/yaml-cpp/src/emitter.o: Walnut/vendor/yaml-cpp/src/emitter.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitter.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.cpp.o

Walnut/vendor/yaml-cpp/src/emitter.i: Walnut/vendor/yaml-cpp/src/emitter.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitter.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.cpp.i

Walnut/vendor/yaml-cpp/src/emitter.s: Walnut/vendor/yaml-cpp/src/emitter.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitter.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitter.cpp.s

Walnut/vendor/yaml-cpp/src/emitterstate.o: Walnut/vendor/yaml-cpp/src/emitterstate.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/emitterstate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterstate.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.cpp.o

Walnut/vendor/yaml-cpp/src/emitterstate.i: Walnut/vendor/yaml-cpp/src/emitterstate.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/emitterstate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterstate.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.cpp.i

Walnut/vendor/yaml-cpp/src/emitterstate.s: Walnut/vendor/yaml-cpp/src/emitterstate.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/emitterstate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterstate.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitterstate.cpp.s

Walnut/vendor/yaml-cpp/src/emitterutils.o: Walnut/vendor/yaml-cpp/src/emitterutils.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/emitterutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterutils.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.cpp.o

Walnut/vendor/yaml-cpp/src/emitterutils.i: Walnut/vendor/yaml-cpp/src/emitterutils.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/emitterutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterutils.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.cpp.i

Walnut/vendor/yaml-cpp/src/emitterutils.s: Walnut/vendor/yaml-cpp/src/emitterutils.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/emitterutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/emitterutils.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/emitterutils.cpp.s

Walnut/vendor/yaml-cpp/src/exceptions.o: Walnut/vendor/yaml-cpp/src/exceptions.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/exceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exceptions.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.cpp.o

Walnut/vendor/yaml-cpp/src/exceptions.i: Walnut/vendor/yaml-cpp/src/exceptions.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/exceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exceptions.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.cpp.i

Walnut/vendor/yaml-cpp/src/exceptions.s: Walnut/vendor/yaml-cpp/src/exceptions.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/exceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exceptions.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/exceptions.cpp.s

Walnut/vendor/yaml-cpp/src/exp.o: Walnut/vendor/yaml-cpp/src/exp.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/exp.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/exp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exp.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/exp.cpp.o

Walnut/vendor/yaml-cpp/src/exp.i: Walnut/vendor/yaml-cpp/src/exp.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/exp.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/exp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exp.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/exp.cpp.i

Walnut/vendor/yaml-cpp/src/exp.s: Walnut/vendor/yaml-cpp/src/exp.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/exp.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/exp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/exp.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/exp.cpp.s

Walnut/vendor/yaml-cpp/src/memory.o: Walnut/vendor/yaml-cpp/src/memory.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/memory.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/memory.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/memory.cpp.o

Walnut/vendor/yaml-cpp/src/memory.i: Walnut/vendor/yaml-cpp/src/memory.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/memory.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/memory.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/memory.cpp.i

Walnut/vendor/yaml-cpp/src/memory.s: Walnut/vendor/yaml-cpp/src/memory.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/memory.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/memory.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/memory.cpp.s

Walnut/vendor/yaml-cpp/src/node.o: Walnut/vendor/yaml-cpp/src/node.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/node.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/node.cpp.o

Walnut/vendor/yaml-cpp/src/node.i: Walnut/vendor/yaml-cpp/src/node.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/node.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/node.cpp.i

Walnut/vendor/yaml-cpp/src/node.s: Walnut/vendor/yaml-cpp/src/node.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/node.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/node.cpp.s

Walnut/vendor/yaml-cpp/src/node_data.o: Walnut/vendor/yaml-cpp/src/node_data.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/node_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node_data.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.cpp.o

Walnut/vendor/yaml-cpp/src/node_data.i: Walnut/vendor/yaml-cpp/src/node_data.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/node_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node_data.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.cpp.i

Walnut/vendor/yaml-cpp/src/node_data.s: Walnut/vendor/yaml-cpp/src/node_data.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/node_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/node_data.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/node_data.cpp.s

Walnut/vendor/yaml-cpp/src/nodebuilder.o: Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.o

Walnut/vendor/yaml-cpp/src/nodebuilder.i: Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.i

Walnut/vendor/yaml-cpp/src/nodebuilder.s: Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/nodebuilder.cpp.s

Walnut/vendor/yaml-cpp/src/nodeevents.o: Walnut/vendor/yaml-cpp/src/nodeevents.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/nodeevents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodeevents.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.cpp.o

Walnut/vendor/yaml-cpp/src/nodeevents.i: Walnut/vendor/yaml-cpp/src/nodeevents.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/nodeevents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodeevents.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.cpp.i

Walnut/vendor/yaml-cpp/src/nodeevents.s: Walnut/vendor/yaml-cpp/src/nodeevents.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/nodeevents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/nodeevents.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/nodeevents.cpp.s

Walnut/vendor/yaml-cpp/src/null.o: Walnut/vendor/yaml-cpp/src/null.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/null.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/null.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/null.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/null.cpp.o

Walnut/vendor/yaml-cpp/src/null.i: Walnut/vendor/yaml-cpp/src/null.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/null.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/null.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/null.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/null.cpp.i

Walnut/vendor/yaml-cpp/src/null.s: Walnut/vendor/yaml-cpp/src/null.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/null.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/null.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/null.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/null.cpp.s

Walnut/vendor/yaml-cpp/src/ostream_wrapper.o: Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.o

Walnut/vendor/yaml-cpp/src/ostream_wrapper.i: Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.i

Walnut/vendor/yaml-cpp/src/ostream_wrapper.s: Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/ostream_wrapper.cpp.s

Walnut/vendor/yaml-cpp/src/parse.o: Walnut/vendor/yaml-cpp/src/parse.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/parse.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parse.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/parse.cpp.o

Walnut/vendor/yaml-cpp/src/parse.i: Walnut/vendor/yaml-cpp/src/parse.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/parse.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parse.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/parse.cpp.i

Walnut/vendor/yaml-cpp/src/parse.s: Walnut/vendor/yaml-cpp/src/parse.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/parse.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parse.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/parse.cpp.s

Walnut/vendor/yaml-cpp/src/parser.o: Walnut/vendor/yaml-cpp/src/parser.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/parser.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parser.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/parser.cpp.o

Walnut/vendor/yaml-cpp/src/parser.i: Walnut/vendor/yaml-cpp/src/parser.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/parser.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parser.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/parser.cpp.i

Walnut/vendor/yaml-cpp/src/parser.s: Walnut/vendor/yaml-cpp/src/parser.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/parser.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/parser.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/parser.cpp.s

Walnut/vendor/yaml-cpp/src/regex_yaml.o: Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.o

Walnut/vendor/yaml-cpp/src/regex_yaml.i: Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.i

Walnut/vendor/yaml-cpp/src/regex_yaml.s: Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/regex_yaml.cpp.s

Walnut/vendor/yaml-cpp/src/scanner.o: Walnut/vendor/yaml-cpp/src/scanner.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanner.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.cpp.o

Walnut/vendor/yaml-cpp/src/scanner.i: Walnut/vendor/yaml-cpp/src/scanner.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanner.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.cpp.i

Walnut/vendor/yaml-cpp/src/scanner.s: Walnut/vendor/yaml-cpp/src/scanner.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanner.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scanner.cpp.s

Walnut/vendor/yaml-cpp/src/scanscalar.o: Walnut/vendor/yaml-cpp/src/scanscalar.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/scanscalar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanscalar.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.cpp.o

Walnut/vendor/yaml-cpp/src/scanscalar.i: Walnut/vendor/yaml-cpp/src/scanscalar.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/scanscalar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanscalar.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.cpp.i

Walnut/vendor/yaml-cpp/src/scanscalar.s: Walnut/vendor/yaml-cpp/src/scanscalar.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/scanscalar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scanscalar.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scanscalar.cpp.s

Walnut/vendor/yaml-cpp/src/scantag.o: Walnut/vendor/yaml-cpp/src/scantag.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/scantag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantag.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.cpp.o

Walnut/vendor/yaml-cpp/src/scantag.i: Walnut/vendor/yaml-cpp/src/scantag.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/scantag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantag.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.cpp.i

Walnut/vendor/yaml-cpp/src/scantag.s: Walnut/vendor/yaml-cpp/src/scantag.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/scantag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantag.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scantag.cpp.s

Walnut/vendor/yaml-cpp/src/scantoken.o: Walnut/vendor/yaml-cpp/src/scantoken.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/scantoken.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantoken.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.cpp.o

Walnut/vendor/yaml-cpp/src/scantoken.i: Walnut/vendor/yaml-cpp/src/scantoken.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/scantoken.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantoken.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.cpp.i

Walnut/vendor/yaml-cpp/src/scantoken.s: Walnut/vendor/yaml-cpp/src/scantoken.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/scantoken.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/scantoken.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/scantoken.cpp.s

Walnut/vendor/yaml-cpp/src/simplekey.o: Walnut/vendor/yaml-cpp/src/simplekey.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/simplekey.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/simplekey.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.cpp.o

Walnut/vendor/yaml-cpp/src/simplekey.i: Walnut/vendor/yaml-cpp/src/simplekey.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/simplekey.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/simplekey.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.cpp.i

Walnut/vendor/yaml-cpp/src/simplekey.s: Walnut/vendor/yaml-cpp/src/simplekey.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/simplekey.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/simplekey.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/simplekey.cpp.s

Walnut/vendor/yaml-cpp/src/singledocparser.o: Walnut/vendor/yaml-cpp/src/singledocparser.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/singledocparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/singledocparser.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.cpp.o

Walnut/vendor/yaml-cpp/src/singledocparser.i: Walnut/vendor/yaml-cpp/src/singledocparser.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/singledocparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/singledocparser.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.cpp.i

Walnut/vendor/yaml-cpp/src/singledocparser.s: Walnut/vendor/yaml-cpp/src/singledocparser.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/singledocparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/singledocparser.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/singledocparser.cpp.s

Walnut/vendor/yaml-cpp/src/stream.o: Walnut/vendor/yaml-cpp/src/stream.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/stream.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/stream.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/stream.cpp.o

Walnut/vendor/yaml-cpp/src/stream.i: Walnut/vendor/yaml-cpp/src/stream.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/stream.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/stream.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/stream.cpp.i

Walnut/vendor/yaml-cpp/src/stream.s: Walnut/vendor/yaml-cpp/src/stream.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/stream.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/stream.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/stream.cpp.s

Walnut/vendor/yaml-cpp/src/tag.o: Walnut/vendor/yaml-cpp/src/tag.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/tag.o

# target to build an object file
Walnut/vendor/yaml-cpp/src/tag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/tag.cpp.o
.PHONY : Walnut/vendor/yaml-cpp/src/tag.cpp.o

Walnut/vendor/yaml-cpp/src/tag.i: Walnut/vendor/yaml-cpp/src/tag.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/tag.i

# target to preprocess a source file
Walnut/vendor/yaml-cpp/src/tag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/tag.cpp.i
.PHONY : Walnut/vendor/yaml-cpp/src/tag.cpp.i

Walnut/vendor/yaml-cpp/src/tag.s: Walnut/vendor/yaml-cpp/src/tag.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/tag.s

# target to generate assembly for a file
Walnut/vendor/yaml-cpp/src/tag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaml-cpp.dir/build.make CMakeFiles/yaml-cpp.dir/Walnut/vendor/yaml-cpp/src/tag.cpp.s
.PHONY : Walnut/vendor/yaml-cpp/src/tag.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cubed-Common-Headless"
	@echo "... Cubed-Server"
	@echo "... Walnut-Headless"
	@echo "... Walnut-Networking"
	@echo "... yaml-cpp"
	@echo "... Cubed-Common/Source/ServerPacket.o"
	@echo "... Cubed-Common/Source/ServerPacket.i"
	@echo "... Cubed-Common/Source/ServerPacket.s"
	@echo "... Cubed-Server/Source/CubedApp.o"
	@echo "... Cubed-Server/Source/CubedApp.i"
	@echo "... Cubed-Server/Source/CubedApp.s"
	@echo "... Cubed-Server/Source/HeadlessConsole.o"
	@echo "... Cubed-Server/Source/HeadlessConsole.i"
	@echo "... Cubed-Server/Source/HeadlessConsole.s"
	@echo "... Cubed-Server/Source/ServerLayer.o"
	@echo "... Cubed-Server/Source/ServerLayer.i"
	@echo "... Cubed-Server/Source/ServerLayer.s"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.o"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.i"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Platform/Linux/Walnut/Networking/LinuxNetworkingUtils.s"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.o"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.i"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Client.s"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.o"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.i"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/NetworkingUtils.s"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.o"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.i"
	@echo "... Walnut/Walnut-Modules/Walnut-Networking/Source/Walnut/Networking/Server.s"
	@echo "... Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.o"
	@echo "... Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.i"
	@echo "... Walnut/Walnut/Platform/Headless/Walnut/ApplicationHeadless.s"
	@echo "... Walnut/Walnut/Source/Walnut/Core/Log.o"
	@echo "... Walnut/Walnut/Source/Walnut/Core/Log.i"
	@echo "... Walnut/Walnut/Source/Walnut/Core/Log.s"
	@echo "... Walnut/Walnut/Source/Walnut/Random.o"
	@echo "... Walnut/Walnut/Source/Walnut/Random.i"
	@echo "... Walnut/Walnut/Source/Walnut/Random.s"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/BufferStream.o"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/BufferStream.i"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/BufferStream.s"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/FileStream.o"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/FileStream.i"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/FileStream.s"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamReader.o"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamReader.i"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamReader.s"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.o"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.i"
	@echo "... Walnut/Walnut/Source/Walnut/Serialization/StreamWriter.s"
	@echo "... Walnut/Walnut/Source/Walnut/Utils/StringUtils.o"
	@echo "... Walnut/Walnut/Source/Walnut/Utils/StringUtils.i"
	@echo "... Walnut/Walnut/Source/Walnut/Utils/StringUtils.s"
	@echo "... Walnut/vendor/yaml-cpp/src/binary.o"
	@echo "... Walnut/vendor/yaml-cpp/src/binary.i"
	@echo "... Walnut/vendor/yaml-cpp/src/binary.s"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.o"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.i"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilder.s"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.o"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.i"
	@echo "... Walnut/vendor/yaml-cpp/src/contrib/graphbuilderadapter.s"
	@echo "... Walnut/vendor/yaml-cpp/src/convert.o"
	@echo "... Walnut/vendor/yaml-cpp/src/convert.i"
	@echo "... Walnut/vendor/yaml-cpp/src/convert.s"
	@echo "... Walnut/vendor/yaml-cpp/src/depthguard.o"
	@echo "... Walnut/vendor/yaml-cpp/src/depthguard.i"
	@echo "... Walnut/vendor/yaml-cpp/src/depthguard.s"
	@echo "... Walnut/vendor/yaml-cpp/src/directives.o"
	@echo "... Walnut/vendor/yaml-cpp/src/directives.i"
	@echo "... Walnut/vendor/yaml-cpp/src/directives.s"
	@echo "... Walnut/vendor/yaml-cpp/src/emit.o"
	@echo "... Walnut/vendor/yaml-cpp/src/emit.i"
	@echo "... Walnut/vendor/yaml-cpp/src/emit.s"
	@echo "... Walnut/vendor/yaml-cpp/src/emitfromevents.o"
	@echo "... Walnut/vendor/yaml-cpp/src/emitfromevents.i"
	@echo "... Walnut/vendor/yaml-cpp/src/emitfromevents.s"
	@echo "... Walnut/vendor/yaml-cpp/src/emitter.o"
	@echo "... Walnut/vendor/yaml-cpp/src/emitter.i"
	@echo "... Walnut/vendor/yaml-cpp/src/emitter.s"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterstate.o"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterstate.i"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterstate.s"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterutils.o"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterutils.i"
	@echo "... Walnut/vendor/yaml-cpp/src/emitterutils.s"
	@echo "... Walnut/vendor/yaml-cpp/src/exceptions.o"
	@echo "... Walnut/vendor/yaml-cpp/src/exceptions.i"
	@echo "... Walnut/vendor/yaml-cpp/src/exceptions.s"
	@echo "... Walnut/vendor/yaml-cpp/src/exp.o"
	@echo "... Walnut/vendor/yaml-cpp/src/exp.i"
	@echo "... Walnut/vendor/yaml-cpp/src/exp.s"
	@echo "... Walnut/vendor/yaml-cpp/src/memory.o"
	@echo "... Walnut/vendor/yaml-cpp/src/memory.i"
	@echo "... Walnut/vendor/yaml-cpp/src/memory.s"
	@echo "... Walnut/vendor/yaml-cpp/src/node.o"
	@echo "... Walnut/vendor/yaml-cpp/src/node.i"
	@echo "... Walnut/vendor/yaml-cpp/src/node.s"
	@echo "... Walnut/vendor/yaml-cpp/src/node_data.o"
	@echo "... Walnut/vendor/yaml-cpp/src/node_data.i"
	@echo "... Walnut/vendor/yaml-cpp/src/node_data.s"
	@echo "... Walnut/vendor/yaml-cpp/src/nodebuilder.o"
	@echo "... Walnut/vendor/yaml-cpp/src/nodebuilder.i"
	@echo "... Walnut/vendor/yaml-cpp/src/nodebuilder.s"
	@echo "... Walnut/vendor/yaml-cpp/src/nodeevents.o"
	@echo "... Walnut/vendor/yaml-cpp/src/nodeevents.i"
	@echo "... Walnut/vendor/yaml-cpp/src/nodeevents.s"
	@echo "... Walnut/vendor/yaml-cpp/src/null.o"
	@echo "... Walnut/vendor/yaml-cpp/src/null.i"
	@echo "... Walnut/vendor/yaml-cpp/src/null.s"
	@echo "... Walnut/vendor/yaml-cpp/src/ostream_wrapper.o"
	@echo "... Walnut/vendor/yaml-cpp/src/ostream_wrapper.i"
	@echo "... Walnut/vendor/yaml-cpp/src/ostream_wrapper.s"
	@echo "... Walnut/vendor/yaml-cpp/src/parse.o"
	@echo "... Walnut/vendor/yaml-cpp/src/parse.i"
	@echo "... Walnut/vendor/yaml-cpp/src/parse.s"
	@echo "... Walnut/vendor/yaml-cpp/src/parser.o"
	@echo "... Walnut/vendor/yaml-cpp/src/parser.i"
	@echo "... Walnut/vendor/yaml-cpp/src/parser.s"
	@echo "... Walnut/vendor/yaml-cpp/src/regex_yaml.o"
	@echo "... Walnut/vendor/yaml-cpp/src/regex_yaml.i"
	@echo "... Walnut/vendor/yaml-cpp/src/regex_yaml.s"
	@echo "... Walnut/vendor/yaml-cpp/src/scanner.o"
	@echo "... Walnut/vendor/yaml-cpp/src/scanner.i"
	@echo "... Walnut/vendor/yaml-cpp/src/scanner.s"
	@echo "... Walnut/vendor/yaml-cpp/src/scanscalar.o"
	@echo "... Walnut/vendor/yaml-cpp/src/scanscalar.i"
	@echo "... Walnut/vendor/yaml-cpp/src/scanscalar.s"
	@echo "... Walnut/vendor/yaml-cpp/src/scantag.o"
	@echo "... Walnut/vendor/yaml-cpp/src/scantag.i"
	@echo "... Walnut/vendor/yaml-cpp/src/scantag.s"
	@echo "... Walnut/vendor/yaml-cpp/src/scantoken.o"
	@echo "... Walnut/vendor/yaml-cpp/src/scantoken.i"
	@echo "... Walnut/vendor/yaml-cpp/src/scantoken.s"
	@echo "... Walnut/vendor/yaml-cpp/src/simplekey.o"
	@echo "... Walnut/vendor/yaml-cpp/src/simplekey.i"
	@echo "... Walnut/vendor/yaml-cpp/src/simplekey.s"
	@echo "... Walnut/vendor/yaml-cpp/src/singledocparser.o"
	@echo "... Walnut/vendor/yaml-cpp/src/singledocparser.i"
	@echo "... Walnut/vendor/yaml-cpp/src/singledocparser.s"
	@echo "... Walnut/vendor/yaml-cpp/src/stream.o"
	@echo "... Walnut/vendor/yaml-cpp/src/stream.i"
	@echo "... Walnut/vendor/yaml-cpp/src/stream.s"
	@echo "... Walnut/vendor/yaml-cpp/src/tag.o"
	@echo "... Walnut/vendor/yaml-cpp/src/tag.i"
	@echo "... Walnut/vendor/yaml-cpp/src/tag.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

