# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake

# The command to remove a file.
RM = /nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /share/sources/glfw-app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /share/sources/glfw-app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/2pbjx4gij8dvgs4cmh01dny1727jy5mi-cmake-3.31.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /share/sources/glfw-app/CMakeFiles /share/sources/glfw-app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /share/sources/glfw-app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named Walnut

# Build rule for target.
Walnut: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Walnut
.PHONY : Walnut

# fast build rule for target.
Walnut/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/build
.PHONY : Walnut/fast

#=============================================================================
# Target rules for targets named WalnutApp

# Build rule for target.
WalnutApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WalnutApp
.PHONY : WalnutApp

# fast build rule for target.
WalnutApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/build
.PHONY : WalnutApp/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb

# Build rule for target.
stb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb
.PHONY : stb

# fast build rule for target.
stb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb.dir/build.make CMakeFiles/stb.dir/build
.PHONY : stb/fast

App/src/Camera.o: App/src/Camera.cpp.o
.PHONY : App/src/Camera.o

# target to build an object file
App/src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Camera.cpp.o
.PHONY : App/src/Camera.cpp.o

App/src/Camera.i: App/src/Camera.cpp.i
.PHONY : App/src/Camera.i

# target to preprocess a source file
App/src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Camera.cpp.i
.PHONY : App/src/Camera.cpp.i

App/src/Camera.s: App/src/Camera.cpp.s
.PHONY : App/src/Camera.s

# target to generate assembly for a file
App/src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Camera.cpp.s
.PHONY : App/src/Camera.cpp.s

App/src/Renderer.o: App/src/Renderer.cpp.o
.PHONY : App/src/Renderer.o

# target to build an object file
App/src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Renderer.cpp.o
.PHONY : App/src/Renderer.cpp.o

App/src/Renderer.i: App/src/Renderer.cpp.i
.PHONY : App/src/Renderer.i

# target to preprocess a source file
App/src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Renderer.cpp.i
.PHONY : App/src/Renderer.cpp.i

App/src/Renderer.s: App/src/Renderer.cpp.s
.PHONY : App/src/Renderer.s

# target to generate assembly for a file
App/src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/Renderer.cpp.s
.PHONY : App/src/Renderer.cpp.s

App/src/WalnutApp.o: App/src/WalnutApp.cpp.o
.PHONY : App/src/WalnutApp.o

# target to build an object file
App/src/WalnutApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/WalnutApp.cpp.o
.PHONY : App/src/WalnutApp.cpp.o

App/src/WalnutApp.i: App/src/WalnutApp.cpp.i
.PHONY : App/src/WalnutApp.i

# target to preprocess a source file
App/src/WalnutApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/WalnutApp.cpp.i
.PHONY : App/src/WalnutApp.cpp.i

App/src/WalnutApp.s: App/src/WalnutApp.cpp.s
.PHONY : App/src/WalnutApp.s

# target to generate assembly for a file
App/src/WalnutApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp.dir/build.make CMakeFiles/WalnutApp.dir/App/src/WalnutApp.cpp.s
.PHONY : App/src/WalnutApp.cpp.s

Walnut/src/Application.o: Walnut/src/Application.cpp.o
.PHONY : Walnut/src/Application.o

# target to build an object file
Walnut/src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Application.cpp.o
.PHONY : Walnut/src/Application.cpp.o

Walnut/src/Application.i: Walnut/src/Application.cpp.i
.PHONY : Walnut/src/Application.i

# target to preprocess a source file
Walnut/src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Application.cpp.i
.PHONY : Walnut/src/Application.cpp.i

Walnut/src/Application.s: Walnut/src/Application.cpp.s
.PHONY : Walnut/src/Application.s

# target to generate assembly for a file
Walnut/src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Application.cpp.s
.PHONY : Walnut/src/Application.cpp.s

Walnut/src/ImGui/imgui_impl_glfw.o: Walnut/src/ImGui/imgui_impl_glfw.cpp.o
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.o

# target to build an object file
Walnut/src/ImGui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_glfw.cpp.o
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.cpp.o

Walnut/src/ImGui/imgui_impl_glfw.i: Walnut/src/ImGui/imgui_impl_glfw.cpp.i
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.i

# target to preprocess a source file
Walnut/src/ImGui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_glfw.cpp.i
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.cpp.i

Walnut/src/ImGui/imgui_impl_glfw.s: Walnut/src/ImGui/imgui_impl_glfw.cpp.s
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.s

# target to generate assembly for a file
Walnut/src/ImGui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_glfw.cpp.s
.PHONY : Walnut/src/ImGui/imgui_impl_glfw.cpp.s

Walnut/src/ImGui/imgui_impl_opengl3.o: Walnut/src/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.o

# target to build an object file
Walnut/src/ImGui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.cpp.o

Walnut/src/ImGui/imgui_impl_opengl3.i: Walnut/src/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.i

# target to preprocess a source file
Walnut/src/ImGui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.cpp.i

Walnut/src/ImGui/imgui_impl_opengl3.s: Walnut/src/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.s

# target to generate assembly for a file
Walnut/src/ImGui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : Walnut/src/ImGui/imgui_impl_opengl3.cpp.s

Walnut/src/Image.o: Walnut/src/Image.cpp.o
.PHONY : Walnut/src/Image.o

# target to build an object file
Walnut/src/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Image.cpp.o
.PHONY : Walnut/src/Image.cpp.o

Walnut/src/Image.i: Walnut/src/Image.cpp.i
.PHONY : Walnut/src/Image.i

# target to preprocess a source file
Walnut/src/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Image.cpp.i
.PHONY : Walnut/src/Image.cpp.i

Walnut/src/Image.s: Walnut/src/Image.cpp.s
.PHONY : Walnut/src/Image.s

# target to generate assembly for a file
Walnut/src/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Image.cpp.s
.PHONY : Walnut/src/Image.cpp.s

Walnut/src/Input/Input.o: Walnut/src/Input/Input.cpp.o
.PHONY : Walnut/src/Input/Input.o

# target to build an object file
Walnut/src/Input/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Input/Input.cpp.o
.PHONY : Walnut/src/Input/Input.cpp.o

Walnut/src/Input/Input.i: Walnut/src/Input/Input.cpp.i
.PHONY : Walnut/src/Input/Input.i

# target to preprocess a source file
Walnut/src/Input/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Input/Input.cpp.i
.PHONY : Walnut/src/Input/Input.cpp.i

Walnut/src/Input/Input.s: Walnut/src/Input/Input.cpp.s
.PHONY : Walnut/src/Input/Input.s

# target to generate assembly for a file
Walnut/src/Input/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Input/Input.cpp.s
.PHONY : Walnut/src/Input/Input.cpp.s

Walnut/src/Random.o: Walnut/src/Random.cpp.o
.PHONY : Walnut/src/Random.o

# target to build an object file
Walnut/src/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Random.cpp.o
.PHONY : Walnut/src/Random.cpp.o

Walnut/src/Random.i: Walnut/src/Random.cpp.i
.PHONY : Walnut/src/Random.i

# target to preprocess a source file
Walnut/src/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Random.cpp.i
.PHONY : Walnut/src/Random.cpp.i

Walnut/src/Random.s: Walnut/src/Random.cpp.s
.PHONY : Walnut/src/Random.s

# target to generate assembly for a file
Walnut/src/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Random.cpp.s
.PHONY : Walnut/src/Random.cpp.s

Walnut/src/Shader.o: Walnut/src/Shader.cpp.o
.PHONY : Walnut/src/Shader.o

# target to build an object file
Walnut/src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Shader.cpp.o
.PHONY : Walnut/src/Shader.cpp.o

Walnut/src/Shader.i: Walnut/src/Shader.cpp.i
.PHONY : Walnut/src/Shader.i

# target to preprocess a source file
Walnut/src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Shader.cpp.i
.PHONY : Walnut/src/Shader.cpp.i

Walnut/src/Shader.s: Walnut/src/Shader.cpp.s
.PHONY : Walnut/src/Shader.s

# target to generate assembly for a file
Walnut/src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Walnut.dir/build.make CMakeFiles/Walnut.dir/Walnut/src/Shader.cpp.s
.PHONY : Walnut/src/Shader.cpp.s

vendor/glad/src/gl.o: vendor/glad/src/gl.c.o
.PHONY : vendor/glad/src/gl.o

# target to build an object file
vendor/glad/src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/vendor/glad/src/gl.c.o
.PHONY : vendor/glad/src/gl.c.o

vendor/glad/src/gl.i: vendor/glad/src/gl.c.i
.PHONY : vendor/glad/src/gl.i

# target to preprocess a source file
vendor/glad/src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/vendor/glad/src/gl.c.i
.PHONY : vendor/glad/src/gl.c.i

vendor/glad/src/gl.s: vendor/glad/src/gl.c.s
.PHONY : vendor/glad/src/gl.s

# target to generate assembly for a file
vendor/glad/src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/vendor/glad/src/gl.c.s
.PHONY : vendor/glad/src/gl.c.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

vendor/stb/stb_image.o: vendor/stb/stb_image.cpp.o
.PHONY : vendor/stb/stb_image.o

# target to build an object file
vendor/stb/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb.dir/build.make CMakeFiles/stb.dir/vendor/stb/stb_image.cpp.o
.PHONY : vendor/stb/stb_image.cpp.o

vendor/stb/stb_image.i: vendor/stb/stb_image.cpp.i
.PHONY : vendor/stb/stb_image.i

# target to preprocess a source file
vendor/stb/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb.dir/build.make CMakeFiles/stb.dir/vendor/stb/stb_image.cpp.i
.PHONY : vendor/stb/stb_image.cpp.i

vendor/stb/stb_image.s: vendor/stb/stb_image.cpp.s
.PHONY : vendor/stb/stb_image.s

# target to generate assembly for a file
vendor/stb/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb.dir/build.make CMakeFiles/stb.dir/vendor/stb/stb_image.cpp.s
.PHONY : vendor/stb/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ImGui"
	@echo "... Walnut"
	@echo "... WalnutApp"
	@echo "... glad"
	@echo "... stb"
	@echo "... App/src/Camera.o"
	@echo "... App/src/Camera.i"
	@echo "... App/src/Camera.s"
	@echo "... App/src/Renderer.o"
	@echo "... App/src/Renderer.i"
	@echo "... App/src/Renderer.s"
	@echo "... App/src/WalnutApp.o"
	@echo "... App/src/WalnutApp.i"
	@echo "... App/src/WalnutApp.s"
	@echo "... Walnut/src/Application.o"
	@echo "... Walnut/src/Application.i"
	@echo "... Walnut/src/Application.s"
	@echo "... Walnut/src/ImGui/imgui_impl_glfw.o"
	@echo "... Walnut/src/ImGui/imgui_impl_glfw.i"
	@echo "... Walnut/src/ImGui/imgui_impl_glfw.s"
	@echo "... Walnut/src/ImGui/imgui_impl_opengl3.o"
	@echo "... Walnut/src/ImGui/imgui_impl_opengl3.i"
	@echo "... Walnut/src/ImGui/imgui_impl_opengl3.s"
	@echo "... Walnut/src/Image.o"
	@echo "... Walnut/src/Image.i"
	@echo "... Walnut/src/Image.s"
	@echo "... Walnut/src/Input/Input.o"
	@echo "... Walnut/src/Input/Input.i"
	@echo "... Walnut/src/Input/Input.s"
	@echo "... Walnut/src/Random.o"
	@echo "... Walnut/src/Random.i"
	@echo "... Walnut/src/Random.s"
	@echo "... Walnut/src/Shader.o"
	@echo "... Walnut/src/Shader.i"
	@echo "... Walnut/src/Shader.s"
	@echo "... vendor/glad/src/gl.o"
	@echo "... vendor/glad/src/gl.i"
	@echo "... vendor/glad/src/gl.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
	@echo "... vendor/stb/stb_image.o"
	@echo "... vendor/stb/stb_image.i"
	@echo "... vendor/stb/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

